version: '3.8'

services:

  mysqldb:
    image: mysql
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=p@ssw0rd1
    volumes:
    - mysql:/var/lib/mysql
    - mysql_config:/etc/mysql

  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - mysqldb

  web2:
    image: fancy_vue_docker 
    ports:
      - "8080:8080"

volumes:
  mysql:
  mysql_config: